package com.johnuckele.vivarium.visualization;

public enum Sprite
{
    FLOOR, WALL, FOOD, HALO_CREATURE_1, HALO_CREATURE_2, HALO_CREATURE_3, RED_CREATURE_1, RED_CREATURE_2, RED_CREATURE_3, BLUE_CREATURE_1, BLUE_CREATURE_2, BLUE_CREATURE_3;
}
