extension plpgsql:
  description: PL/pgSQL procedural language
  owner: postgres
  schema: pg_catalog
  version: '1.0'
schema public:
  description: standard public schema
  owner: postgres
  privileges:
  - postgres:
    - all
  - PUBLIC:
    - all
  table job_dependencies:
    columns:
    - job_id:
        type: uuid
    - requires_job_id:
        type: uuid
    foreign_keys:
      job_dependencies_job_id_fkey:
        columns:
        - job_id
        references:
          columns:
          - id
          schema: public
          table: jobs
      job_dependencies_requires_job_id_fkey:
        columns:
        - requires_job_id
        references:
          columns:
          - id
          schema: public
          table: jobs
    owner: vivarium
    unique_constraints:
      job_dependencies_job_id_requires_job_id_key:
        columns:
        - job_id
        - requires_job_id
  table job_input_resources:
    columns:
    - job_id:
        type: uuid
    - resource_id:
        type: uuid
    foreign_keys:
      job_input_resources_job_id_fkey:
        columns:
        - job_id
        references:
          columns:
          - id
          schema: public
          table: jobs
      job_input_resources_resource_id_fkey:
        columns:
        - resource_id
        references:
          columns:
          - id
          schema: public
          table: resources
    owner: vivarium
    unique_constraints:
      job_input_resources_job_id_resource_id_key:
        columns:
        - job_id
        - resource_id
  table job_output_resources:
    columns:
    - job_id:
        type: uuid
    - resource_id:
        type: uuid
    foreign_keys:
      job_output_resources_job_id_fkey:
        columns:
        - job_id
        references:
          columns:
          - id
          schema: public
          table: jobs
      job_output_resources_resource_id_fkey:
        columns:
        - resource_id
        references:
          columns:
          - id
          schema: public
          table: resources
    owner: vivarium
    unique_constraints:
      job_output_resources_job_id_resource_id_key:
        columns:
        - job_id
        - resource_id
  table job_properties:
    columns:
    - job_id:
        type: uuid
    - property_name:
        type: text
    - property_value:
        type: text
    foreign_keys:
      job_properties_job_id_fkey:
        columns:
        - job_id
        references:
          columns:
          - id
          schema: public
          table: jobs
    owner: vivarium
    unique_constraints:
      job_properties_job_id_property_name_key:
        columns:
        - job_id
        - property_name
  table jobs:
    columns:
    - id:
        not_null: true
        type: uuid
    - job_type:
        type: job_type
    - status:
        not_null: true
        type: job_status
    - priority:
        not_null: true
        type: smallint
    - checked_out_by:
        type: uuid
    - checked_out_time:
        type: timestamp with time zone
    - completed_time:
        type: timestamp with time zone
    foreign_keys:
      jobs_checked_out_by_fkey:
        columns:
        - checked_out_by
        references:
          columns:
          - id
          schema: public
          table: workers
    owner: vivarium
    primary_key:
      jobs_pkey:
        columns:
        - id
  table resources:
    columns:
    - id:
        not_null: true
        type: uuid
    - data:
        type: text
    - file_format_version:
        type: integer
    - world_count:
        type: integer
    - blueprint_count:
        type: integer
    - species_count:
        type: integer
    - creature_count:
        type: integer
    - brain_count:
        type: integer
    owner: vivarium
    primary_key:
      resources_pkey:
        columns:
        - id
  table workers:
    columns:
    - id:
        not_null: true
        type: uuid
    - is_active:
        type: boolean
    - last_activity:
        type: timestamp with time zone
    - file_format_version:
        not_null: true
        type: integer
    - throughputs:
        not_null: true
        type: bigint[]
    - code_version:
        not_null: true
        type: integer[]
    owner: vivarium
    primary_key:
      workers_pkey:
        columns:
        - id
  type job_status:
    labels:
    - BLOCKED
    - WAITING
    - PROCESSING
    - DONE
    owner: vivarium
  type job_type:
    labels:
    - CREATE_WORLD
    - RUN_SIMULATION
    owner: vivarium

