extension plpgsql:
  description: PL/pgSQL procedural language
  owner: postgres
  schema: pg_catalog
  version: '1.0'
schema public:
  description: standard public schema
  owner: postgres
  privileges:
  - postgres:
    - all
  - PUBLIC:
    - all
  table create_world_jobs:
    columns:
    - job_id:
        not_null: true
        type: uuid
    - source_resource_id:
        not_null: true
        type: uuid
    - output_resource_id:
        not_null: true
        type: uuid
    foreign_keys:
      create_world_jobs_output_resource_id_fkey:
        columns:
        - output_resource_id
        references:
          columns:
          - id
          schema: public
          table: resources
      create_world_jobs_source_resource_id_fkey:
        columns:
        - source_resource_id
        references:
          columns:
          - id
          schema: public
          table: resources
    owner: vivarium
    primary_key:
      create_world_jobs_pkey:
        columns:
        - job_id
  table job_dependencies:
    columns:
    - job_id:
        type: uuid
    - requires_job_id:
        type: uuid
    foreign_keys:
      job_dependencies_job_id_fkey:
        columns:
        - job_id
        references:
          columns:
          - id
          schema: public
          table: jobs
      job_dependencies_requires_job_id_fkey:
        columns:
        - requires_job_id
        references:
          columns:
          - id
          schema: public
          table: jobs
    owner: vivarium
    unique_constraints:
      job_dependencies_job_id_requires_job_id_key:
        columns:
        - job_id
        - requires_job_id
  table jobs:
    columns:
    - id:
        not_null: true
        type: uuid
    - status:
        not_null: true
        type: job_status
    - priority:
        not_null: true
        type: smallint
    - checked_out_by:
        type: uuid
    - checked_out_time:
        type: timestamp with time zone
    - completed_time:
        type: timestamp with time zone
    foreign_keys:
      jobs_checked_out_by_fkey:
        columns:
        - checked_out_by
        references:
          columns:
          - id
          schema: public
          table: workers
    owner: vivarium
    primary_key:
      jobs_pkey:
        columns:
        - id
  table resources:
    columns:
    - id:
        not_null: true
        type: uuid
    - data:
        type: text
    - file_format_version:
        type: integer
    - world_count:
        type: integer
    - blueprint_count:
        type: integer
    - species_count:
        type: integer
    - creature_count:
        type: integer
    - brain_count:
        type: integer
    owner: vivarium
    primary_key:
      resources_pkey:
        columns:
        - id
  table simulation_jobs:
    columns:
    - job_id:
        not_null: true
        type: uuid
    - end_tick:
        not_null: true
        type: bigint
    - source_resource_id:
        not_null: true
        type: uuid
    - output_resource_id:
        not_null: true
        type: uuid
    foreign_keys:
      simulation_jobs_output_resource_id_fkey:
        columns:
        - output_resource_id
        references:
          columns:
          - id
          schema: public
          table: resources
      simulation_jobs_source_resource_id_fkey:
        columns:
        - source_resource_id
        references:
          columns:
          - id
          schema: public
          table: resources
    owner: vivarium
    primary_key:
      simulation_jobs_pkey:
        columns:
        - job_id
  table throughputs:
    columns:
    - worker_id:
        type: uuid
    - slots:
        type: smallint
    - throughput:
        type: integer
    foreign_keys:
      throughputs_worker_id_fkey:
        columns:
        - worker_id
        references:
          columns:
          - id
          schema: public
          table: workers
    owner: vivarium
    unique_constraints:
      throughputs_worker_id_slots_key:
        columns:
        - worker_id
        - slots
  table workers:
    columns:
    - id:
        not_null: true
        type: uuid
    - is_active:
        type: boolean
    - last_activity:
        type: timestamp with time zone
    owner: vivarium
    primary_key:
      workers_pkey:
        columns:
        - id
  type job_status:
    labels:
    - blocked
    - waiting
    - processing
    - done
    owner: vivarium

