extension plpgsql:
  description: PL/pgSQL procedural language
  owner: postgres
  schema: pg_catalog
  version: '1.0'
schema public:
  description: standard public schema
  owner: postgres
  privileges:
  - postgres:
    - all
  - PUBLIC:
    - all
  table create_world_jobs:
    check_constraints:
      create_world_type_check:
        columns:
        - job_type
        expression: (job_type = 'create_world'::job_type)
    columns:
    - id:
        inherited: true
        not_null: true
        type: uuid
    - job_type:
        inherited: true
        type: job_type
    - status:
        inherited: true
        not_null: true
        type: job_status
    - priority:
        inherited: true
        not_null: true
        type: smallint
    - checked_out_by:
        inherited: true
        type: uuid
    - checked_out_time:
        inherited: true
        type: timestamp with time zone
    - completed_time:
        inherited: true
        type: timestamp with time zone
    - source_resource_id:
        inherited: true
        type: uuid
    - output_resource_id:
        inherited: true
        type: uuid
    inherits:
    - pipe_jobs
    owner: vivarium
  table job_dependencies:
    columns:
    - job_id:
        type: uuid
    - requires_job_id:
        type: uuid
    foreign_keys:
      job_dependencies_job_id_fkey:
        columns:
        - job_id
        references:
          columns:
          - id
          schema: public
          table: jobs
      job_dependencies_requires_job_id_fkey:
        columns:
        - requires_job_id
        references:
          columns:
          - id
          schema: public
          table: jobs
    owner: vivarium
    unique_constraints:
      job_dependencies_job_id_requires_job_id_key:
        columns:
        - job_id
        - requires_job_id
  table jobs:
    columns:
    - id:
        not_null: true
        type: uuid
    - job_type:
        type: job_type
    - status:
        not_null: true
        type: job_status
    - priority:
        not_null: true
        type: smallint
    - checked_out_by:
        type: uuid
    - checked_out_time:
        type: timestamp with time zone
    - completed_time:
        type: timestamp with time zone
    foreign_keys:
      jobs_checked_out_by_fkey:
        columns:
        - checked_out_by
        references:
          columns:
          - id
          schema: public
          table: workers
    owner: vivarium
    primary_key:
      jobs_pkey:
        columns:
        - id
  table pipe_jobs:
    columns:
    - id:
        inherited: true
        not_null: true
        type: uuid
    - job_type:
        inherited: true
        type: job_type
    - status:
        inherited: true
        not_null: true
        type: job_status
    - priority:
        inherited: true
        not_null: true
        type: smallint
    - checked_out_by:
        inherited: true
        type: uuid
    - checked_out_time:
        inherited: true
        type: timestamp with time zone
    - completed_time:
        inherited: true
        type: timestamp with time zone
    - source_resource_id:
        type: uuid
    - output_resource_id:
        type: uuid
    foreign_keys:
      pipe_jobs_output_resource_id_fkey:
        columns:
        - output_resource_id
        references:
          columns:
          - id
          schema: public
          table: resources
      pipe_jobs_source_resource_id_fkey:
        columns:
        - source_resource_id
        references:
          columns:
          - id
          schema: public
          table: resources
    inherits:
    - jobs
    owner: vivarium
  table resources:
    columns:
    - id:
        not_null: true
        type: uuid
    - data:
        type: text
    - file_format_version:
        type: integer
    - world_count:
        type: integer
    - blueprint_count:
        type: integer
    - species_count:
        type: integer
    - creature_count:
        type: integer
    - brain_count:
        type: integer
    owner: vivarium
    primary_key:
      resources_pkey:
        columns:
        - id
  table run_simulation_jobs:
    check_constraints:
      create_world_type_check:
        columns:
        - job_type
        expression: (job_type = 'run_simulation'::job_type)
    columns:
    - id:
        inherited: true
        not_null: true
        type: uuid
    - job_type:
        inherited: true
        type: job_type
    - status:
        inherited: true
        not_null: true
        type: job_status
    - priority:
        inherited: true
        not_null: true
        type: smallint
    - checked_out_by:
        inherited: true
        type: uuid
    - checked_out_time:
        inherited: true
        type: timestamp with time zone
    - completed_time:
        inherited: true
        type: timestamp with time zone
    - source_resource_id:
        inherited: true
        type: uuid
    - output_resource_id:
        inherited: true
        type: uuid
    - end_tick:
        not_null: true
        type: bigint
    inherits:
    - pipe_jobs
    owner: vivarium
  table workers:
    columns:
    - id:
        not_null: true
        type: uuid
    - is_active:
        type: boolean
    - last_activity:
        type: timestamp with time zone
    - file_format_version:
        not_null: true
        type: integer
    - throughputs:
        not_null: true
        type: bigint[]
    - code_version:
        not_null: true
        type: integer[]
    owner: vivarium
    primary_key:
      workers_pkey:
        columns:
        - id
  type job_status:
    labels:
    - blocked
    - waiting
    - processing
    - done
    owner: vivarium
  type job_type:
    labels:
    - create_world
    - run_simulation
    owner: vivarium

