package com.johnuckele.vivarium.visualization;

public enum RenderCode
{
	WORLD_MAP, BRAIN_WEIGHTS,
	SIMPLE_UCKELEOID, COMPLEX_UCKELEOID,
	FULL_UCKELEOID_LIST, LIVE_UCKELEOID_LIST, DEAD_UCKELEOID_LIST
}
